### ISSUE TITLE
Bot connects but not works.

### ISSUE THREAD

**Issue by CoderTheNaked** [WickrInc/wickrio-hello-world-bot#10]
Hello dear developers, happy new years..

Tried to work with hello-world-bot but it not works. 

What did i do?
- Created Bot user at my Wickrme Admin Panel
- docker run -v /opt/WickrIO:/opt/WickrIO -ti wickr/bot-cloud:latest  and completed other process at documentary of WickrIO.

I can create conservation with my bot, i see its in my network but not answering messages at conservation or in a room. What can be problem?

**Comment by pwcushman** [comment]
An updated version of the wickrio-hello-world-bot was published recently. 
Please use the version (specifically the package.json) from the v5.38 branch for now.  We are in the process of moving to version 10 of node, but those docker images have not been exposed yet.  The v5.38 version of the wickrio-hello-world-bot integration works with the 5.38.x version of the addon, which is based on version 8 of node.
