### ISSUE TITLE
Bot starts with an error. Not doing conversation

### ISSUE THREAD

**Issue by CoderTheNaked** [WickrInc/wickrio-hello-world-bot#11]
(node:140) UnhandledPromiseRejectionWarning: Error: Failed to create getClientState command. action 'get_state' unknown!
at /opt/WickrIO/clients/nigbot/integration/wickrio-hello-world-bot/node_modules/wickrio-bot-api/WickrIOBot.js:36:41
at new Promise (<anonymous>)
at /opt/WickrIO/clients/nigbot/integration/wickrio-hello-world-bot/node_modules/wickrio-bot-api/WickrIOBot.js:24:20
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
at Function.Module.runMain (module.js:696:11)
at startup (bootstrap_node.js:204:16)
at bootstrap_node.js:625:3
(node:140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, o$
(node:140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js$

**Comment by pwcushman** [comment]
See my comment to your previous issue.  It is likely that the wrong version of the bot api is loaded.

**Comment by CoderTheNaked** [comment]
(wickrio bot api)
"version": "5.38.14"
(wickrio addon)
"version": "5.38.17"
(wickrio-hello-world-bot)
"version": "5.38.18"

**Comment by pwcushman** [comment]
The wickrio bot api version should be 5.38.15, that is the latest and has a change to which addon it is dependent on.  But the wickrio addon you have is correct, as well as the wickrio-hello-world-bot version.  But that shouldn't actually matter.

Please on the Docker CLI can you run the "version" command and let me know what it says.

**Comment by CoderTheNaked** [comment]
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by pwcushman** [comment]
Actually I'm looking for the version of the WickrIO docker image you are using, or the tag.

**Comment by CoderTheNaked** [comment]
Is that needed one?
Welcome to the WickrIO Console program (v4.64.5.1)

**Comment by pwcushman** [comment]
Do you know which docker image you are using?  For example wickr/bot-cloud or wickr/bot-enterprise

**Comment by CoderTheNaked** [comment]
It's wickr/bot-cloud.

What did i do at beginning? Installed docker via ssh. docker pull wickr/bot-cloud:latest and im running
docker run -v /opt/WickrIO:/opt/WickrIO -ti wickr/bot-cloud:latest

**Comment by pwcushman** [comment]
That's fine.  We are in the process of updating everything.  Can you please try the new version I just posted up:

docker run -v /opt/WickrIO:/opt/WickrIO -ti wickr/bot-cloud:v5.38

**Comment by CoderTheNaked** [comment]
Great. Thanks!! 

Hey there! Thanks for messaging me! I have a few helpful but random tips I can share in response to your messages, so please bear with me If you have more questions than I have answers, head to Settings > Support in Wickr Pro. Way to go to protect your privacy!

I'm going to close this Issue. 

- docker run -v /opt/WickrIO:/opt/WickrIO -ti wickr/bot-cloud:latest : is not downloading latest bot cloud.

so better to use 

docker run -v /opt/WickrIO:/opt/WickrIO -ti wickr/bot-cloud:v5.38 (this is the lastest ver for today)

other process are same. 

Good job dear pwcushman
